### ISSUE TITLE
Запекание анимации

### ISSUE THREAD

**Issue by s30-zip** [igelbox/blender-retarget#2]
Не получается запечь анимацию, после запекания и удаления "донора" конечный скелет просто стоит.

**Comment by igelbox** [comment]
@s30-zip как и всегда, не плохо бы примерчик какой-нибудь простой. Загрузи, пожалуйста, blend-файл с примером.

**Comment by s30-zip** [comment]
Пример https://yadi.sk/d/AcRTuyTl3XkpGz

**Comment by s30-zip** [comment]
Вроде получилось. Нужно после запекания ("донора" можно отключить) очистить данные анимации https://yadi.sk/i/2Ru6ubd73YHtMs потом в редакторе действий выбрать нашу анимку и вроде работает, правда в иерархии остаются ещё nla треки и после экспорта анимации вылазит какое-то предупреждение https://yadi.sk/i/XLQ_OHUy3YHtMv , но при импорте .skl вроде всё работает https://yadi.sk/d/5yR4fI1R3YHtN7 https://yadi.sk/d/-kaIjOGY3YHtMo

**Comment by igelbox** [comment]
Better late than never)

> после экспорта анимации вылазит какое-то предупреждение

Это уже к другому аддону относится - https://github.com/PavelBlend/blender-xray. А так, там написано что-то про unsupported bone curve. Думаю, это из-за того, что у каких-то костей был выставлен режим отличный от Euler или Quaternion.

**Comment by igelbox** [comment]
Если проблема всё ещё актуальна, то переоткрой, пожалуйста эту ишью снова.
