### ISSUE TITLE
Hello, how to bake animation after retarging?

### ISSUE THREAD

**Issue by SXDIST** [igelbox/blender-retarget#24]

**Comment by igelbox** [comment]
Hi @Diablo-1337,
this plugin doesn't provide (nor restrict you of choosing) any baking tools. I've done it this way intentionally coz it makes the retargeting adjustments quicker w/o requiring to re-bake the animation each time.
So, I do believe it's better to find over the internet any tool for baking you'd like and use it for re-targeted armature.
