### ISSUE TITLE
Scripts of retargeting

### ISSUE THREAD

**Issue by gemlongman** [igelbox/blender-retarget#6]
Is there some examples of python scripts for batch retargeting animation form a bvh to another bvh？
could it export skeleton map file and be imported by a batch  scripts？

**Comment by igelbox** [comment]
Probably, I didn't quite get your point. But, you need manually align target armature bones as it outlined in https://github.com/igelbox/blender-retarget#how-to-use
> Position target bones along with source ones, to make the target armature almost the same pose as the source one

So, I cannot grasp how this manual action would be done during a script. As an option, you may use `bpy.ops.animation_retarget.copy_mapping` operator just after aligning the armature to get the relative positioning data, then use `bpy.ops.animation_retarget.paste_mapping` operator to apply this data on next armature in your batch (if the next target armature looks pretty the same as the first one).

As for
> could it export skeleton map file and be imported by a batch scripts？

Not yet. Actually, there is the `bpy.ops.animation_retarget.copy_mapping` and `bpy.ops.animation_retarget.paste_mapping` operators. So, if you could add some code to save/load values from Blender's clipboard this may fit your requirements.

Also, if you could explain your workflow in more details, I might be able to provide some much-sophisticated workarounds.

**Comment by gemlongman** [comment]
Thank you so much!
> Position target bones along with source ones, to make the target armature almost the same pose as the source one
> Actually, there is the bpy.ops.animation_retarget.copy_mapping and bpy.ops.animation_retarget.paste_mapping operators. 
It is still very helpful, while there are thousands of animation files  with a T pose frame which is same as target  bones. Unfortunately, most of animation files don't start at a standard pose. So I have to try some thing else. But this is very valuable!

**Comment by igelbox** [comment]
>  Unfortunately, most of animation files don't start at a standard pose.

This addon doesn't rely on nor requires any of the armatures to be in a standard pose. Actually, it should work just fine with any source animations of any poses. But the user just needs to align the target armature accordingly.

**Comment by gemlongman** [comment]
Actually, I just want to batch retarget lots of animations  to a custom skeleton only with a bones map.

**Comment by igelbox** [comment]
OK. If you could give some examples (e.g. links to BVH files and target armatures) then I probably may figure out some approach/automatization.

**Comment by gemlongman** [comment]
There are three animations which I want to retarget to the target skeleton.
[sample.zip](https://github.com/igelbox/blender-retarget/files/4393460/sample.zip)

The animations are downloaded from https://accad.osu.edu/research/motion-lab/mocap-system-and-data
and the skeleton is downloaded from https://www.mixamo.com/ ,and is transfered to bvh by Motionbuilder.

Actually it maybe a different problem and will take some time, I still appreciate so much!
